#!/bin/sh
root_path="$HOME/repos/go/src"

check_results_and_fail () {
  if [ $? -ne 0 ]; then
    echo "Failed..."
    exit 1
  fi
}

[ -z "$1" ] && echo "no argument given" &&  exit 1
if [ "$1" = "-h" ]; then 
  echo "[c]reate [g]o [p]roject"
  echo "-----------------------"
  echo "creates a go project at \"$root_path/\$1\""
  echo ""
  echo "Usage"
  echo "-----"
  echo "$0 <location>"
  echo ""
  echo ""
  exit 1
fi
# check if root dir exists
if [ -d "$root_path" ]
then
  echo "$root_path present"
else
  echo "$root_path not present"
  echo "creating $root_path"
  mkdir -p "$root_path"
fi
check_results_and_fail
echo "Creating new go project in $root_path/$1"
cd $root_path
check_results_and_fail
mkdir $1
check_results_and_fail
cd $1
check_results_and_fail
git init
check_results_and_fail
mkdir cmd
check_results_and_fail
mkdir internal
check_results_and_fail
mkdir pkg
check_results_and_fail
go mod init github.com/nerdwave-nick/$1
check_results_and_fail

